server {
    listen 127.0.0.1:8080;
    server_name _;

    root /usr/share/nginx/html;
    location / {
        index index.html index.htm;
    }

    error_log off;
    access_log off;
}

server {
    listen 127.0.0.1:8444 ssl;
    server_name _;

    ssl_certificate     /home/mtproxy/runtime/fallback.crt;
    ssl_certificate_key /home/mtproxy/runtime/fallback.key;

    root /usr/share/nginx/html;
    location / {
        index index.html index.htm;
    }

    error_log off;
    access_log off;
}
